title:        Indie EdTech Data Jam
url:          http://kinlane.github.io/indie-edtech-data-jam
logo:         http://kinlane-productions.s3.amazonaws.com/api-evangelist/api-evangelist-logo-400.png

logo_width:   55
logo_bottom_padding: 10

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 250
paginate_path: "/updates/page:num"

categories_path : /categories.html
tags_path : /tags.html

# Masthead title
masthead_link: http://kinlane.github.io/indie-edtech-data-jam/
masthead_font_size: 85
masthead_title: '{"APIs"}'

# Feature
feature_title: API Design Providers Guide
feature_link: http://apis.how/xzca4kr2wb
feature_image_source: https://s3.amazonaws.com/kinlane-productions/whitepapers/3scale/report-image-api-design.png
feature_image_width: 45

# Project
project_image: https://s3.amazonaws.com/kinlane-productions/bw-icons/bw-robots.jpeg
project_summary: This is a research project to help me better understand exactly what a bot is these days, and how APIs are used as engines for these increasingly aware, active, nuggets of compute. I am looking at how APIs are used to drive bots, but also how are bots employed via API driven platforms like Twitter, and Slack.

# Navigation
navigation:
  - label1: Project Overview
    link1: /indie-edtech-data-jam/
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 0
    padding: 0
    decorate: 0
  - label1: What is a website?
    link1: /indie-edtech-data-jam/what-is-a-website/
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 60
    padding: 25
    decorate: 0
  - label1: What is an API?
    link1: /indie-edtech-data-jam/what-is-an-api/
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 60
    padding: 5
    decorate: 0
  - label1: The History of APIs
    link1: /indie-edtech-data-jam/history-of-apis/
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 60
    padding: 5
    decorate: 0
  - label1: The Programmable Web
    link1: /indie-edtech-data-jam/programmable-web/
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 60
    padding: 5
    decorate: 0
  - label1: Some APIs In Your World
    link1: /indie-edtech-data-jam/apis/
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 60
    padding: 5
    decorate: 0
  - label1: Mapping Our API World
    link1: /indie-edtech-data-jam/mapping/
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 60
    padding: 5
    decorate: 0
  - label1: Putting APIs To Work
    link1: /indie-edtech-data-jam/putting-apis-to-work/
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 60
    padding: 5
    decorate: 0
  - label1: The University API
    link1: /indie-edtech-data-jam/unversitiy-api/
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 60
    padding: 5
    decorate: 0
  - label1: The Personal APIs
    link1: /indie-edtech-data-jam/personal-apis/
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 60
    padding: 5
    decorate: 0
  - label1: Return to API Evangelist
    link1: http://apievangelist.com
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 10
    padding: 25
    decorate: 1

# Footer Navigation
footernavigation:
  - label: API 100K View
    link: http://apievangelist.com
  - label: updates
    link: /updates/
  - label: Partners
    link: http://apievangelist.com/partners/
  - label: APIs.json
    link: http://apisjson.org
  - label: About Kin Lane
    link: http://kinlane.com
  - label: Branding Guidelines
    link: http://apievangelist.com/branding-guidelines.html
  - label: Contact
    link: http://kinlane.com/contacts/

# sponsors
sponsors_margin_top: 15
sponsors_padding_top: 3
sponsors_json_url: https://s3.amazonaws.com/kinlane-productions/json/sponsors.json
